sudo: false

language: haskell

cache:
  directories:
    - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack setup --no-terminal
  - stack build --only-snapshot --no-terminal

script:
  - stack --no-terminal --skip-ghc-check test

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.2
