editor:
  command: 'gvim'
  options:
    - '--nofork'
    - '%'
  place_holder: '%'
trash:
  command: 'trash-put'
  options:
    - '%'
  place_holder: '%'
options:
  - -c
  - 2
  - -i
  - LICENSE
  - -I
  - ^\.git
